export const courses = [
  {
    id: 1,
    title: "DA with Python & SQL",
    desc: "Introducing the Data Analysis with Python and SQL Certification Course, a comprehensive beginner to expert program designed to help aspiring data analysts to learn the essential skills in the rapidly growing field of data analysis. This course offers a unique blend of practical and theoretical knowledge, combining the powerful programming language Python and the versatile database management system SQL to help you analyze, visualize, and interpret data efficiently. By the end of the course, you will have the confidence to tackle real-world data challenges and make data-driven decisions that can significantly impact your organization. Join us to transform your passion for data into a rewarding career.",
    img: "/courses/one.png",
    content:
      "This comprehensive course covers data cleaning, analysis, visualization, and querying. You will work on real-world datasets and gain hands-on experience using Python and SQL.",
    syllabus: [
      "Introduction to Data Analysis",
      "Python Basics",
      "Pandas & NumPy",
      "SQL Fundamentals",
      "Data Visualization",
      "Statistics for Data Analysis",
      "Capstone Project",
    ],
    duration: "4 months",
    enrolled: 250,
    tutor: "Dr. Emily Bere",
    weeks: 8,
    ratings: 4.6,
    ratingsCount: 1200,
    lastUpdated: "12/2025",
    totalLectures: 45,
    totalDuration: "10h 30m",
    requirements: [
      "No programming experience needed",
      "A computer with Python installed",
      "Basic math knowledge"
    ],
    profilepic: "/teachers/teacherone.png",
    instructorBio: "Dr. Emily Bere is a data scientist with 10 years of experience in industry and academia."
  },
  {
    id: 2,
    title: "Machine Learning",
    desc: "The Machine Learning Certification Course is an extensive program designed to guide learners from beginner to advanced levels in the exciting field of machine learning. This course combines both theoretical concepts and practical applications, focusing on using Python and various libraries to build and implement machine learning models. By the end of the course, you’ll be equipped as a proficient Machine Learning Engineer ready to address real-world problems through machine learning techniques and contribute to data-driven decision-making in any organization. Join us to transform your enthusiasm for technology into a successful career in machine learning.",
    img: "/courses/two.png",
    content:
      "Learn machine learning algorithms, model evaluation, feature engineering, and deployment using real datasets.",
    syllabus: [
      "ML Fundamentals",
      "Regression & Classification",
      "Clustering",
      "Dimensionality Reduction",
      "Model Evaluation",
      "Ensemble Methods",
      "Final Project",
    ],
    duration: "3 months",
    enrolled: 180,
    tutor: "Prof. Michael Peterson",
    weeks: 10,
    ratings: 4.7,
    ratingsCount: 950,
    lastUpdated: "11/2025",
    totalLectures: 55,
    totalDuration: "12h",
    requirements: [
      "Basic Python knowledge",
      "Understanding of statistics",
      "Access to a computer"
    ],
    profilepic: "/teachers/teachertwo.png",
    instructorBio: "Prof. Michael Peterson is a machine learning expert with numerous publications and industry projects."
  },
  {
    id: 3,
    title: "Data Engineering",
    desc: "The Data Engineering Course is a robust, hands-on program designed to equip learners with the skills required to design, build, and manage scalable data infrastructure. This course focuses on transforming raw data into reliable, structured datasets that power analytics, machine learning, and business intelligence systems. You will learn how to build efficient ETL pipelines, work with both SQL and NoSQL databases, and process large-scale data using modern big data frameworks such as Apache Spark and Airflow. By the end of the course, you will be confident in developing production-ready data pipelines and supporting data-driven organizations as a professional data engineer.",
    img: "/courses/three.png",
    content:
      "This course teaches modern data engineering tools including Spark, Airflow, and cloud-based data platforms.",
    syllabus: [
      "Data Engineering Overview",
      "SQL & NoSQL Databases",
      "ETL Pipelines",
      "Big Data with Spark",
      "Airflow",
      "Cloud Data Platforms",
      "Pipeline Project",
    ],
    duration: "5 months",
    enrolled: 120,
    tutor: "Sarah Thompson",
    weeks: 12,
    ratings: 4.5,
    ratingsCount: 600,
    lastUpdated: "10/2025",
    totalLectures: 60,
    totalDuration: "15h",
    requirements: [
      "Basic programming skills",
      "Familiarity with databases",
      "Cloud computing basics"
    ],
    profilepic: "/teachers/teacherthree.png",
    instructorBio: "Sarah Thompson is a senior data engineer at a leading tech company with expertise in big data technologies."
  },
  {
    id: 4,
    title: "Visualization & Dashboarding",
    desc: "The Visualization & Dashboarding Course is designed to help learners transform complex datasets into clear, interactive, and impactful visual stories. This course emphasizes data storytelling, visual best practices, and dashboard design using industry-leading tools such as Tableau, Power BI, and Python visualization libraries. You will learn how to create insightful dashboards that drive business decisions and communicate findings effectively to both technical and non-technical audiences. By the end of this course, you will have a strong portfolio of professional dashboards and the skills needed to excel as a data visualization specialist or business intelligence analyst.",
    img: "/courses/four.png",
    content:
      "Learn Tableau, Power BI, and Python visualization tools to build interactive dashboards.",
    syllabus: [
      "Data Visualization Principles",
      "Tableau Basics",
      "Power BI Fundamentals",
      "Dashboard Design",
      "Advanced Charts",
      "Python Visualization",
      "Dashboard Project",
    ],
    duration: "1 month",
    enrolled: 300,
    tutor: "Wisdom China",
    weeks: 6,
    ratings: 4.8,
    ratingsCount: 1500,
    lastUpdated: "1/2026",
    totalLectures: 35,
    totalDuration: "7h 45m",
    requirements: [
      "No prior experience required",
      "Access to visualization tools",
      "Interest in data storytelling"
    ],
    profilepic: "/teachers/teacherfour.png",
    instructorBio: "Wisdom China is a visualization specialist who has designed dashboards for Fortune 500 companies."
  },
  {
    id: 5,
    title: "Artificial Intelligence",
    desc: "The Artificial Intelligence Course is a comprehensive program designed to introduce learners to the core concepts and real-world applications of AI. This course covers key areas such as machine learning foundations, natural language processing, computer vision, and ethical considerations in AI systems. Through hands-on projects and practical implementations using Python, you will learn how to build intelligent systems capable of solving complex problems. By the end of the course, you will be equipped with the knowledge and confidence to develop AI-powered applications and pursue advanced roles in artificial intelligence and emerging technologies.",
    img: "/courses/five.png",
    content:
      "Explore NLP, computer vision, and ethical AI while building real AI-powered solutions.",
    syllabus: [
      "AI Fundamentals",
      "Python for AI",
      "Natural Language Processing",
      "Computer Vision",
      "AI Ethics",
      "AI Applications",
      "AI Project",
    ],
    duration: "3 months",
    enrolled: 200,
    tutor: "Dr. Lisa Adaku",
    weeks: 10,
    ratings: 4.7,
    ratingsCount: 1100,
    lastUpdated: "11/2025",
    totalLectures: 50,
    totalDuration: "11h",
    requirements: [
      "Python programming experience",
      "Basic math and statistics",
      "Curiosity about AI"
    ],
    profilepic: "/teachers/teacherfive.png",
    instructorBio: "Dr. Lisa Adaku is an AI researcher with a PhD in computer science and several patents in AI technologies."
  },
  {
    id: 6,
    title: "Excel & Power BI Mastery",
    desc: "Our data analysis with Excel training course is designed to provide you with a comprehensive understanding of how to analyze and manipulate data using Microsoft Excel. Whether you're new to Excel or looking to enhance your skills, our course will equip you with the knowledge and tools you need to effectively analyze data and make informed decisions. Our experienced instructors will guide you through real-world examples and case studies to help you apply your new skills to practical scenarios. You will have the opportunity to work on hands-on exercises and projects to solidify your understanding of the concepts covered in the course. By the end of the course, you will have the ability to perform data analysis tasks using Excel with confidence. You will be able to understand and analyze complex data sets and present your findings in a clear and concise manner. You will also have a solid foundation to build upon should you choose to pursue more advanced data analysis techniques.",
    img: "/courses/six.png",
    content:
      "Master advanced Excel functions, Power Query, DAX, and Power BI dashboards.",
    syllabus: [
      "Advanced Excel",
      "Data Modeling",
      "Power Query",
      "Power BI Basics",
      "DAX Mastery",
      "Interactive Reports",
      "BI Dashboard Project",
    ],
    duration: "3 months",
    enrolled: 350,
    tutor: "Robert King",
    weeks: 7,
    ratings: 4.5,
    ratingsCount: 1800,
    lastUpdated: "12/2025",
    totalLectures: 40,
    totalDuration: "9h",
    requirements: [
      "Basic Excel knowledge",
      "Access to Microsoft tools",
      "Interest in business intelligence"
    ],
    profilepic: "/teachers/teachersix.png",
    instructorBio: "Robert King is a certified Power BI expert with over 15 years in business analytics."
  },
];