export const instructor = [
    {
        id: 1,
        name: "Lugard wisdom",
        role: "Excutive Director",
        company: "Scippra Academy",
        image: "/instructors/ceo.png",
        experience: "4-5 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 2,
        name: "Jane Amaka",
        role: "Word Press Instructor",
        company: "Scippra Academy",
        image: "/instructors/jane.png",
        experience: "2-3 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 3,
        name: "Peter John",
        role: "Frontend Developer",
        company: "Scippra Academy",
        image: "/instructors/john.png",
        experience: "1-2 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 4,
        name: "Mary Smith",
        role: "Data Science Instructor",
        company: "Scippra Academy",
        image: "/instructors/mary.png",
        experience: "3-4 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 5,
        name: "David Brown",
        role: "Backend Instructor",
        company: "Scippra Academy",
        image: "/instructors/david.png",
        experience: "2-3 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 6,
        name: "Susan Lee",
        role: "Full Stack Developer",
        company: "Scippra Academy",
        image: "/instructors/susan.png",
        experience: "2-3 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 7,
        name: "Michael Johnson",
        role: "Graphic Design Instructor",
        company: "Scippra Academy",
        image: "/instructors/michael.png",
        experience: "3-4 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 8,
        name: "Danto emmanuel",
        role: "3d modeling Instructor",
        company: "Scippra Academy",
        image: "/instructors/danto.png",
        experience: "3-4 Exp",
        location: "Port Harcourt, Nigeria",
    }
]