export const jobs = [
  {
    id: 1,
    title: "Web Developer",
    company: "Imac Technology",
    location: "Abuja",
    amount: "₦250,000",
    email: "imac@gmail.com",
    contact: "09064583473",
    requirement: ["Next.js", "Vue.js", "Angular", "GitHub"],
  },
  {
    id: 2,
    title: "Frontend Developer",
    company: "TechNova Ltd",
    location: "Lagos",
    amount: "₦300,000",
    email: "hr@technova.com",
    contact: "08123456789",
    requirement: ["React.js", "Tailwind CSS", "JavaScript", "REST APIs"],
  },
  {
    id: 3,
    title: "Backend Developer",
    company: "CodeWave Solutions",
    location: "Remote",
    amount: "₦350,000",
    email: "careers@codewave.io",
    contact: "07099887766",
    requirement: ["Django", "Node.js", "PostgreSQL", "API Development"],
  },
  {
    id: 4,
    title: "Mobile App Developer",
    company: "Appify Africa",
    location: "Ibadan",
    amount: "₦280,000",
    email: "jobs@appify.africa",
    contact: "08033445566",
    requirement: ["React Native", "Flutter", "Firebase", "Play Store Deployment"],
  },
  {
    id: 5,
    title: "UI/UX Designer",
    company: "PixelCraft Studio",
    location: "Lagos",
    amount: "₦220,000",
    email: "design@pixelcraft.com",
    contact: "09011223344",
    requirement: ["Figma", "Adobe XD", "User Research", "Prototyping"],
  },
  {
    id: 6,
    title: "Data Analyst",
    company: "Insight Analytics",
    location: "Abuja",
    amount: "₦320,000",
    email: "recruitment@insight.com",
    contact: "08166778899",
    requirement: ["Python", "SQL", "Power BI", "Excel"],
  },
  {
    id: 7,
    title: "DevOps Engineer",
    company: "CloudNet Systems",
    location: "Remote",
    amount: "₦450,000",
    email: "devops@cloudnet.io",
    contact: "07044556677",
    requirement: ["Docker", "AWS", "CI/CD", "Linux"],
  },
  {
    id: 8,
    title: "Digital Marketing Specialist",
    company: "GrowthHub",
    location: "Port Harcourt",
    amount: "₦200,000",
    email: "marketing@growthhub.com",
    contact: "08055667788",
    requirement: ["SEO", "Google Ads", "Content Strategy", "Analytics"],
  },
];


export const instructor = [
    {
        id: 1,
        name: "Lugard wisdom",
        role: "Excutive Director",
        company: "Scippra Academy",
        image: "/instructors/ceo.png",
        experience: "4-5 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 2,
        name: "Jane Amaka",
        role: "Word Press Instructor",
        company: "Scippra Academy",
        image: "/instructors/jane.png",
        experience: "2-3 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 3,
        name: "Peter John",
        role: "Frontend Developer",
        company: "Scippra Academy",
        image: "/instructors/john.png",
        experience: "1-2 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 4,
        name: "Mary Smith",
        role: "Data Science Instructor",
        company: "Scippra Academy",
        image: "/instructors/mary.png",
        experience: "3-4 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 5,
        name: "David Brown",
        role: "Backend Instructor",
        company: "Scippra Academy",
        image: "/instructors/david.png",
        experience: "2-3 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 6,
        name: "Susan Lee",
        role: "Full Stack Developer",
        company: "Scippra Academy",
        image: "/instructors/susan.png",
        experience: "2-3 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 7,
        name: "Michael Johnson",
        role: "Graphic Design Instructor",
        company: "Scippra Academy",
        image: "/instructors/michael.png",
        experience: "3-4 Exp",
        location: "Port Harcourt, Nigeria",
    },
    {
        id: 8,
        name: "Danto Emmanuel",
        role: "3d modeling Instructor",
        company: "Scippra Academy",
        image: "/instructors/danto.png",
        experience: "3-4 Exp",
        location: "Port Harcourt, Nigeria",
    }
]